apiVersion: v1
kind: Namespace
metadata:
  name: mailpit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  namespace: mailpit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
        - name: mailpit
          image: axllent/mailpit:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1025
              name: smtp
            - containerPort: 8025
              name: web
          env:
            - name: MP_MAX_MESSAGES
              value: "5000"
            - name: MP_DATABASE
              value: "/data/mailpit.db"
            - name: MP_SMTP_AUTH_ACCEPT_ANY
              value: "1"
            - name: MP_SMTP_AUTH_ALLOW_INSECURE
              value: "1"
          volumeMounts:
            - name: mailpit-data
              mountPath: /data
      restartPolicy: Always
      volumes:
        - name: mailpit-data
          persistentVolumeClaim:
            claimName: mailpit-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailpit-pvc
  namespace: mailpit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mailpit
  namespace: mailpit
spec:
  selector:
    app: mailpit
  type: ClusterIP
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
    - name: web
      port: 8025
      targetPort: 8025
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mailpit
  namespace: mailpit
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: mailpit.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mailpit
                port:
                  number: 8025

